services:
    rabbitmq:
        build: .
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
            - 1883:1883
        volumes:
            - ./dados:/var/lib/rabbitmq/        